/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroToHeroRouteImport } from './routes/zero-to-hero'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as OnlineTrainingsRouteImport } from './routes/online-trainings'
import { Route as NrityaSadhanaRouteImport } from './routes/nritya-sadhana'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPayEnrollmentIdRouteImport } from './routes/_authenticated/pay.$enrollmentId'
import { Route as AuthenticatedPayBundlePurchaseIdRouteImport } from './routes/_authenticated/pay-bundle.$purchaseId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ZeroToHeroRoute = ZeroToHeroRouteImport.update({
  id: '/zero-to-hero',
  path: '/zero-to-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineTrainingsRoute = OnlineTrainingsRouteImport.update({
  id: '/online-trainings',
  path: '/online-trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const NrityaSadhanaRoute = NrityaSadhanaRouteImport.update({
  id: '/nritya-sadhana',
  path: '/nritya-sadhana',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPayEnrollmentIdRoute =
  AuthenticatedPayEnrollmentIdRouteImport.update({
    id: '/pay/$enrollmentId',
    path: '/pay/$enrollmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayBundlePurchaseIdRoute =
  AuthenticatedPayBundlePurchaseIdRouteImport.update({
    id: '/pay-bundle/$purchaseId',
    path: '/pay-bundle/$purchaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/pay-bundle/$purchaseId': typeof AuthenticatedPayBundlePurchaseIdRoute
  '/pay/$enrollmentId': typeof AuthenticatedPayEnrollmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/pay-bundle/$purchaseId': typeof AuthenticatedPayBundlePurchaseIdRoute
  '/pay/$enrollmentId': typeof AuthenticatedPayEnrollmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/pay-bundle/$purchaseId': typeof AuthenticatedPayBundlePurchaseIdRoute
  '/_authenticated/pay/$enrollmentId': typeof AuthenticatedPayEnrollmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/pay-bundle/$purchaseId'
    | '/pay/$enrollmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/pay-bundle/$purchaseId'
    | '/pay/$enrollmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/pay-bundle/$purchaseId'
    | '/_authenticated/pay/$enrollmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  NrityaSadhanaRoute: typeof NrityaSadhanaRoute
  OnlineTrainingsRoute: typeof OnlineTrainingsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VerifyRoute: typeof VerifyRoute
  WorkshopsRoute: typeof WorkshopsRoute
  ZeroToHeroRoute: typeof ZeroToHeroRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-to-hero': {
      id: '/zero-to-hero'
      path: '/zero-to-hero'
      fullPath: '/zero-to-hero'
      preLoaderRoute: typeof ZeroToHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-trainings': {
      id: '/online-trainings'
      path: '/online-trainings'
      fullPath: '/online-trainings'
      preLoaderRoute: typeof OnlineTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nritya-sadhana': {
      id: '/nritya-sadhana'
      path: '/nritya-sadhana'
      fullPath: '/nritya-sadhana'
      preLoaderRoute: typeof NrityaSadhanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pay/$enrollmentId': {
      id: '/_authenticated/pay/$enrollmentId'
      path: '/pay/$enrollmentId'
      fullPath: '/pay/$enrollmentId'
      preLoaderRoute: typeof AuthenticatedPayEnrollmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay-bundle/$purchaseId': {
      id: '/_authenticated/pay-bundle/$purchaseId'
      path: '/pay-bundle/$purchaseId'
      fullPath: '/pay-bundle/$purchaseId'
      preLoaderRoute: typeof AuthenticatedPayBundlePurchaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPayBundlePurchaseIdRoute: typeof AuthenticatedPayBundlePurchaseIdRoute
  AuthenticatedPayEnrollmentIdRoute: typeof AuthenticatedPayEnrollmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPayBundlePurchaseIdRoute: AuthenticatedPayBundlePurchaseIdRoute,
  AuthenticatedPayEnrollmentIdRoute: AuthenticatedPayEnrollmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  NrityaSadhanaRoute: NrityaSadhanaRoute,
  OnlineTrainingsRoute: OnlineTrainingsRoute,
  TestimonialsRoute: TestimonialsRoute,
  VerifyRoute: VerifyRoute,
  WorkshopsRoute: WorkshopsRoute,
  ZeroToHeroRoute: ZeroToHeroRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
