/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroToHeroRouteImport } from './routes/zero-to-hero'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as OnlineTrainingsRouteImport } from './routes/online-trainings'
import { Route as NrityaSadhanaRouteImport } from './routes/nritya-sadhana'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ZeroToHeroRoute = ZeroToHeroRouteImport.update({
  id: '/zero-to-hero',
  path: '/zero-to-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineTrainingsRoute = OnlineTrainingsRouteImport.update({
  id: '/online-trainings',
  path: '/online-trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const NrityaSadhanaRoute = NrityaSadhanaRouteImport.update({
  id: '/nritya-sadhana',
  path: '/nritya-sadhana',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/nritya-sadhana': typeof NrityaSadhanaRoute
  '/online-trainings': typeof OnlineTrainingsRoute
  '/testimonials': typeof TestimonialsRoute
  '/verify': typeof VerifyRoute
  '/workshops': typeof WorkshopsRoute
  '/zero-to-hero': typeof ZeroToHeroRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/admin'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/nritya-sadhana'
    | '/online-trainings'
    | '/testimonials'
    | '/verify'
    | '/workshops'
    | '/zero-to-hero'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  NrityaSadhanaRoute: typeof NrityaSadhanaRoute
  OnlineTrainingsRoute: typeof OnlineTrainingsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VerifyRoute: typeof VerifyRoute
  WorkshopsRoute: typeof WorkshopsRoute
  ZeroToHeroRoute: typeof ZeroToHeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-to-hero': {
      id: '/zero-to-hero'
      path: '/zero-to-hero'
      fullPath: '/zero-to-hero'
      preLoaderRoute: typeof ZeroToHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-trainings': {
      id: '/online-trainings'
      path: '/online-trainings'
      fullPath: '/online-trainings'
      preLoaderRoute: typeof OnlineTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nritya-sadhana': {
      id: '/nritya-sadhana'
      path: '/nritya-sadhana'
      fullPath: '/nritya-sadhana'
      preLoaderRoute: typeof NrityaSadhanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  NrityaSadhanaRoute: NrityaSadhanaRoute,
  OnlineTrainingsRoute: OnlineTrainingsRoute,
  TestimonialsRoute: TestimonialsRoute,
  VerifyRoute: VerifyRoute,
  WorkshopsRoute: WorkshopsRoute,
  ZeroToHeroRoute: ZeroToHeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
